# Generated by Django 3.1.8 on 2021-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
